services:
  web:
    build: 
      dockerfile: nginx.dockerfile
      context: .
    ports:
      - "8080:8080"
    restart: always
  get2buga:
    build: 
      dockerfile: get2buga.dockerfile
      context: .
    ports:
      - "80:80"
    restart: always
  db:
    image: mariadb:latest
    volumes:
      - get2buga:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    command:
      - "--env MARIADB_PASSWORD=^3O*Pp928Adj"
volumes:
  get2buga:
  